apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webshop
  name: nginx-exam
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webshop
  strategy:
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: webshop
        service: nginx
    spec:
      containers:
        - image: nginx:1.9
          name: nginx
          resources: {}
status: {}
