apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1312-pv
  labels:
    type: local
  namespace: ckad-1312
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/lab1312"
