apiVersion: v1
kind: Pod
metadata:
  name: pod1312
  labels:
    name: pod1312
  namespace: ckad-1312
spec:
  volumes:
    - name: pvst
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: pod1312
      image: nginx
      volumeMounts:
        - mountPath: "/webdata"
          name: pvst
