apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  namespace: ckad-ns2
  labels:
    name: alpine-pod
spec:
  containers:
    - name: alpine-pod
      image: alpine
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: my-config
