apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: ckad-ns1
  labels:
    name: pod-a
spec:
  containers:
    - name: pod-a
      image: httpd

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: ckad-ns1
  labels:
    name: pod-b
spec:
  containers:
    - name: nginx-img
      image: nginx
    - name: apline-img
      image: alpine
      command: ["sleep", "3600"]
