apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: ckad-ns3
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      hostPath:
        path: "/pddfile"
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/log/date.txt; sleep 5; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /var/log
    - name: log-collector
      image: alpine
      command: ["/bin/ls", "/var/log/date.txt"]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: shared-data
          mountPath: /var/log
