apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    type: nginx-dep
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      type: nginx-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        type: nginx-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
